### ISSUE TITLE
Account for frequencies and beta-values

### ISSUE THREAD

**Issue by soren-rand** [HimesGroup/snpsettest#1]
Hi HimesGroup 

Thank you for providing an easy method for harmonizing summary stats to references. I am currently trying to harmonize three summary statistics to 1000 Genomes reference, in order to provide a uniform format for a meta-analysis. 
However, a caveat - as I see it - is the inability to calculate frequencies and flip beta values. Is there a possibility to do this with the current method? Or do you know how to sort this problem, once the harmonization is done? 

Best wishes 
Soren

**Comment by jaehyunjoo** [comment]
Hi Soren, 

Thanks for your interest in our package. It does not support allele frequencies and the sign of beta values in harmonization as the scope of this package is VEGAS gene-based test that does not require that information. We possibly implement to return logical indices indicating allele swapping so that you could post-process beta values and allele frequencies but it would take some time.  

All the best, 
Jaehyun

**Comment by soren-rand** [comment]
Hi Jaehyun, 

Thanks for your quick response. I appreciate it :-) 
I understand. I would be happy to finally use such a tool, if you choose to do it one day! Wish you the greatest of luck with everything. Thanks for the support. 

Soren! 👍

**Comment by jaehyunjoo** [comment]
@soren-rand you could try the following:

```R
remotes::install_github("HimesGroup/snpsettest@dev")
library(snpsettest)

bfile <- system.file("extdata", "example.bed", package = "snpsettest")
x <- read_reference_bed(bfile, verbose = FALSE)

hsumstats <- harmonize_sumstats(exGWAS, x, match_by_id = FALSE,
                                return_indice = TRUE)
hsumstats[(swapped_), ]
#          id chr     pos A1 A2     pvalue          key_ swapped_
# 1:    SNP_0   1   50215  C  G 0.19693530   1_50215_G_C     TRUE
# 2: SNP_1165   1  316786  C  G 0.06326722  1_316786_G_C     TRUE
# 3: SNP_4757   1 1142706  C  G 0.37023671 1_1142706_G_C     TRUE
```

I added `return_indice` argument to return additional columns: **key_** and **swapped_** (also **flipped_** if `check_strand_flip = TRUE`). **key_** represents a combination of chr, pos, A1, and A2 in the function input (e.g., exGWAS here) so that the harmonized output could be re-mapped to other info such as beta and allele frequencies in your original data. **swapped_** indicates whether the match is with swapped alleles. 

You could use **swapped_** to post-process beta values or risk allele frequencies. Note that `return_indice` only works when `match_by_id = FALSE`. As illustrated in the code snippet above, you should install the package from the dev branch because we haven't pushed it to CRAN yet. Please check your results carefully as new functionality might contain errors. 

Best, 
Jaehyun

**Comment by soren-rand** [comment]
Hi again Jaehyun,

That's awesome man, I really appreciate it. Will give it a try and try to make it happen. Once again, I thank you sincerely for your effort and hard work for making this happen in the first place! :D Cheers friend!

Best
Soren

**Comment by jaehyunjoo** [comment]
The updated version is now available on CRAN.
